// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SMIXKTBConvenienceCheque.Models
{
    [Table("BatchControl")]
    public partial class BatchControl
    {
        public BatchControl()
        {
            BatchFileNos = new HashSet<BatchFileNo>();
            ChequeDetails = new HashSet<ChequeDetail>();
        }

        [Key]
        public int BatchControlId { get; set; }
        public int? FileNo { get; set; }
        [StringLength(100)]
        [Unicode(false)]
        public string BatchControlCode { get; set; }
        public int? ItemCount { get; set; }
        [Column(TypeName = "decimal(18, 2)")]
        public decimal? SumAmount { get; set; }
        [Column(TypeName = "date")]
        public DateTime? EffectiveDate { get; set; }
        public bool? IsActive { get; set; }
        public DateTime? CreatedDate { get; set; }
        public int? CreatedByUserId { get; set; }
        public DateTime? UpdatedDate { get; set; }
        public int? UpdatedByUserId { get; set; }

        [InverseProperty("BatchControl")]
        public virtual ICollection<BatchFileNo> BatchFileNos { get; set; }
        [InverseProperty("BatchControl")]
        public virtual ICollection<ChequeDetail> ChequeDetails { get; set; }
    }
}