// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SMIXKTBConvenienceCheque.Models
{
    [Table("BatchOutPutDetail")]
    public partial class BatchOutPutDetail
    {
        [Key]
        public int BatchOutPutDetailId { get; set; }
        public int? BatchOutPutHeaderId { get; set; }
        [StringLength(1)]
        [Unicode(false)]
        public string RecordType { get; set; }
        /// <summary>
        /// ชื่อย่อบริษัท
        /// </summary>
        [StringLength(10)]
        [Unicode(false)]
        public string CompanyAbbreviation { get; set; }
        /// <summary>
        /// ชื่อบริษัทผู้สั่งจ่ายเช็ค
        /// </summary>
        [StringLength(100)]
        [Unicode(false)]
        public string CompanyName { get; set; }
        /// <summary>
        /// ที่อยู่บริษัทผู้สั่งจ่ายเช็ค
        /// </summary>
        [StringLength(70)]
        [Unicode(false)]
        public string Address1 { get; set; }
        /// <summary>
        /// ที่อยู่บริษัทผู้สั่งจ่ายเช็ค
        /// </summary>
        [StringLength(70)]
        [Unicode(false)]
        public string Address2 { get; set; }
        /// <summary>
        /// ที่อยู่บริษัทผู้สั่งจ่ายเช็ค
        /// </summary>
        [StringLength(70)]
        [Unicode(false)]
        public string Address3 { get; set; }
        /// <summary>
        /// หมายเลขบัญชีที่ตัดจ่ายเช็ค
        /// </summary>
        [StringLength(20)]
        [Unicode(false)]
        public string PayeeAccountNumber { get; set; }
        /// <summary>
        /// เลขประจำตัวผู้เสียภาษีของบริษัทผู้สั่งจ่ายเช็ค
        /// </summary>
        [StringLength(15)]
        [Unicode(false)]
        public string PayeeTaxIdNumber { get; set; }
        /// <summary>
        /// เลขประกันสังคมของบริษัทผู้สั่งจ่ายเช็ค
        /// </summary>
        [StringLength(15)]
        [Unicode(false)]
        public string SocialSecurityId { get; set; }
        /// <summary>
        /// ลำดับที่ของรายการที่มีการเปลี่ยนแปลงสถานะ
        /// </summary>
        [StringLength(6)]
        [Unicode(false)]
        public string Sequence { get; set; }
        /// <summary>
        /// รหัสอ้างอิงการชำระเงินที่บริษัทส่งมา
        /// </summary>
        [StringLength(20)]
        [Unicode(false)]
        public string PaymentRefNo1 { get; set; }
        /// <summary>
        /// วันทีพิมพ์บนหน้าเช็ค
        /// </summary>
        [StringLength(8)]
        [Unicode(false)]
        public string ChequeEffectiveDate { get; set; }
        /// <summary>
        /// หมายเลขเช็ค
        /// </summary>
        [StringLength(10)]
        [Unicode(false)]
        public string ChequeNumber { get; set; }
        /// <summary>
        /// ชื่อผู้รับเช็ค
        /// </summary>
        [StringLength(100)]
        [Unicode(false)]
        public string PayeeName { get; set; }
        /// <summary>
        /// จำนวนเงินหักภาษี ณ ที่จ่าย
        /// </summary>
        [StringLength(20)]
        [Unicode(false)]
        public string WithholdingTaxAmount { get; set; }
        /// <summary>
        /// จำนวนเงินจ่ายสุทธิ (ตามเช็ค)
        /// </summary>
        [StringLength(20)]
        [Unicode(false)]
        public string NetCheque { get; set; }
        /// <summary>
        /// สถานะของเช็ค
        /// I :   Issue  ออกเช็คแล้ว
        /// D :   Deliver  รับเช็คแล้ว
        /// P :   Paid  เช็คเรียกเก็บแล้ว
        /// R :   Return ส่งเช็คคืนบริษัท
        /// S :   Stop  อายัดเช็ค
        /// C :   Canceled  ยกเลิกเช็ค
        /// 
        /// </summary>
        [StringLength(5)]
        [Unicode(false)]
        public string ChequeStatus { get; set; }
        /// <summary>
        /// วันที่สถานะเช็คเปลี่ยนแปลง
        /// </summary>
        [StringLength(8)]
        [Unicode(false)]
        public string TransactionDate { get; set; }
        /// <summary>
        /// วันทีพิมพ์เช็ค
        /// </summary>
        [StringLength(8)]
        [Unicode(false)]
        public string OutwardDate { get; set; }
        /// <summary>
        /// จำนวนเช็คทั้งหมดที่มีการเปลี่ยนแปลง
        /// </summary>
        [StringLength(6)]
        [Unicode(false)]
        public string TotalRecords { get; set; }
        public string BatchData { get; set; }
        [StringLength(1)]
        [Unicode(false)]
        public string DataType { get; set; }
        public bool? IsActive { get; set; }
        public DateTime? CreatedDate { get; set; }
        public int? CreatedByUserId { get; set; }
        public DateTime? UpdatedDate { get; set; }
        public int? UpdatedByUserId { get; set; }

        [ForeignKey("BatchOutPutHeaderId")]
        [InverseProperty("BatchOutPutDetails")]
        public virtual BatchOutPutHeader BatchOutPutHeader { get; set; }
    }
}