// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SMIXKTBConvenienceCheque.Models
{
    [Table("BatchOutPutHeader")]
    public partial class BatchOutPutHeader
    {
        public BatchOutPutHeader()
        {
            BatchOutPutDetails = new HashSet<BatchOutPutDetail>();
        }

        [Key]
        public int BatchOutPutHeaderId { get; set; }
        [StringLength(100)]
        [Unicode(false)]
        public string BatchOutPutHeaderCode { get; set; }
        [StringLength(255)]
        public string FileName { get; set; }
        public int? ItemCount { get; set; }
        [Column(TypeName = "decimal(18, 2)")]
        public decimal? SumAmount { get; set; }
        public bool? IsActive { get; set; }
        public DateTime? CreatedDate { get; set; }
        public int? CreatedByUserId { get; set; }
        public DateTime? UpdatedDate { get; set; }
        public int? UpdatedByUserId { get; set; }

        [InverseProperty("BatchOutPutHeader")]
        public virtual ICollection<BatchOutPutDetail> BatchOutPutDetails { get; set; }
    }
}