// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SMIXKTBConvenienceCheque.Models
{
    [Table("BatchFileNo")]
    public partial class BatchFileNo
    {
        public BatchFileNo()
        {
            BatchDetails = new HashSet<BatchDetail>();
            BatchHeaders = new HashSet<BatchHeader>();
        }

        [Key]
        public int BatchFileNoId { get; set; }
        public int? BatchControlId { get; set; }
        public int? ItemCount { get; set; }
        [Column(TypeName = "decimal(18, 2)")]
        public decimal? SumAmount { get; set; }
        public int? BatchNo { get; set; }
        [Column(TypeName = "date")]
        public DateTime? UploadDate { get; set; }
        public bool? IsActive { get; set; }
        public DateTime? CreatedDate { get; set; }
        public int? CreatedByUserId { get; set; }
        public DateTime? UpdatedDate { get; set; }
        public int? UpdatedByUserId { get; set; }

        [ForeignKey("BatchControlId")]
        [InverseProperty("BatchFileNos")]
        public virtual BatchControl BatchControl { get; set; }
        [InverseProperty("BatchFileNo")]
        public virtual ICollection<BatchDetail> BatchDetails { get; set; }
        [InverseProperty("BatchFileNo")]
        public virtual ICollection<BatchHeader> BatchHeaders { get; set; }
    }
}