// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SMIXKTBConvenienceCheque.Models
{
    [Table("BatchHeader")]
    public partial class BatchHeader
    {
        [Key]
        public int BatchHeaderId { get; set; }
        public int? BatchFileNoId { get; set; }
        [StringLength(20)]
        [Unicode(false)]
        public string AppId { get; set; }
        public int? ItemCount { get; set; }
        [Column(TypeName = "decimal(18, 2)")]
        public decimal? SumAmount { get; set; }
        public bool? IsActive { get; set; }
        public DateTime? CreatedDate { get; set; }
        public int? CreatedByUserId { get; set; }
        public DateTime? UpdatedDate { get; set; }
        public int? UpdatedByUserId { get; set; }

        [ForeignKey("BatchFileNoId")]
        [InverseProperty("BatchHeaders")]
        public virtual BatchFileNo BatchFileNo { get; set; }
    }
}