// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SMIXKTBConvenienceCheque.Models
{
    [Keyless]
    [Table("TmpImportClaim")]
    public partial class TmpImportClaim
    {
        public Guid ClaimExportTransactionId { get; set; }
        [StringLength(20)]
        [Unicode(false)]
        public string ClaimCode { get; set; }
        [StringLength(20)]
        [Unicode(false)]
        public string CustomerDetailCode { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string ApplicationCode { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string PolicyNo { get; set; }
        [StringLength(255)]
        public string SchoolName { get; set; }
        [StringLength(255)]
        public string CustName { get; set; }
        [Column(TypeName = "decimal(16, 2)")]
        public decimal? PayTotal { get; set; }
        [StringLength(20)]
        [Unicode(false)]
        public string ClaimNo { get; set; }
        public int? BranchId { get; set; }
        [StringLength(255)]
        public string BranchDetail { get; set; }
        [StringLength(20)]
        [Unicode(false)]
        public string School_id { get; set; }
        [StringLength(20)]
        [Unicode(false)]
        public string SubDistrictCode { get; set; }
        [StringLength(255)]
        public string SubDistrict { get; set; }
        [StringLength(255)]
        public string District { get; set; }
        [StringLength(255)]
        public string Province { get; set; }
        [StringLength(20)]
        [Unicode(false)]
        public string ZipCode { get; set; }
        public int? FileNo { get; set; }
        public int? SeqNo { get; set; }
        public int? BatchNo { get; set; }
        [StringLength(20)]
        [Unicode(false)]
        public string Reference2 { get; set; }
        [StringLength(20)]
        [Unicode(false)]
        public string Reference3 { get; set; }
        [StringLength(20)]
        [Unicode(false)]
        public string SchoolRunning { get; set; }
    }
}