// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using SMIXKTBConvenienceCheque.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace SMIXKTBConvenienceCheque.Data
{
    public partial interface IAppDBContextProcedures
    {
        Task<List<usp_ReportCheque_SelectResult>> usp_ReportCheque_SelectAsync(string ChequeStatus, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
